### PR TITLE
Remove nuget support and dependencies 

### PR DESCRIPTION
**Pull request by ashtat**
With UPM support there's no need for nuget. The sample has been updated as well to source the spatializer from the UPM feed.

### CODE REVIEW

**Comment by MikeChemi** [comment]
Also need to remove nuget references from readme

**Comment by ashtat** [comment]
> Also need to remove nuget references from readme

Yes, I'll update.

**Comment by MikeChemi** [comment]
And then I guess you'll update the docs page after this goes in? https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/spatial-sound-in-unity

**Review by MikeChemi — APPROVED** [review]

**Comment by ashtat** [comment]
> > Also need to remove nuget references from readme
> 
> Yes, I'll update.

Strange though, I thought I updated the readme.

**Comment by ashtat** [comment]
> And then I guess you'll update the docs page after this goes in? https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/spatial-sound-in-unity

Yes, that will be when we pull into master and do another release. Current release still supports nuget.

**Comment by ashtat** [comment]
> > > Also need to remove nuget references from readme
> > 
> > 
> > Yes, I'll update.
> 
> Strange though, I thought I updated the readme.

Note to self: Save files after modifications. :)

**Pull request merged**
